spring:
  application:
    name: aurora-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/aurora_dev
    username: postgres
    password: PravPost90@123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080

logging:
  level:
    org.springframework: INFO
    org.hibernate.SQL: INFO

jwt:
  secret: 4b0d6c0b8d89b3a3f8d5f5d0b0c2a8f1d4c7e9a2b6f1c3d8e5f7a9b1c2d3e4f5
  expiration: 86400000